plugins:
  sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
{{ if .Plugins }}
  required:
{{ range $key, $value := .Plugins }}
    {{ $key }}: {{ $value }}
{{ end }}
{{ end }}
jenkins:
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  mode: NORMAL
  numExecutors: {{ .Executors }}
  primaryView:
    all:
      name: "all"
  quietPeriod: 5
  scmCheckoutRetryCount: 3
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: "{{.User}}"
          password: "{{.Password}}"
  slaveAgentPort: {{ .AgentPort }}
  systemMessage: "jenkins-operator managed Jenkins instance\n\n"
  views:
    - all:
        name: "all"
jobs:
  - script: >
      freeStyleJob('create-jenkins-jobs') {
          blockOn('*') {
              blockLevel('GLOBAL')
              scanQueueFor('ALL')
          }

          description('JobDSL job, that creates other jobs')
          displayName('Create new jobs')

          parameters {
              fileParam('job.dsl', 'JobDSL file')
          }


          steps {
              dsl {
                  external('job.dsl')
              }
          }
      }
security:
  remotingCLI:
    enabled: false
unclassified:
  location:
    adminAddress: {{.AdminEmail}}
    url: {{.Url}}
tool:
  git:
    installations:
      - home: "git"
        name: "Default"
  jdk:
    defaultProperties:
      - installSource:
          installers:
            - jdkInstaller:
                acceptLicense: false
