type: chart
builds:
  - image: samsung_cnct/jenkins-operator
    context: jenkins-operator
    chart: jenkins-operator
    tagValue: image.tag
    dockerContext: .
deployments:
  - chart: jenkins-operator
    timeout: 600
    retries: 2
    setAppVersion: true
    release: jo-pipeline
    test:
      values:
        - key: chartCrds
          value: false
        - key: nameOverride
          value: jo-pipeline
prod:
  doDeploy: none
