apiVersion: jenkins.jenkinsoperator.maratoid.github.com/v1alpha1
kind: JenkinsInstance
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: jenkinsinstance-sample
spec:
  image: "jenkins/jenkins:lts"
  env:
    SOME_ENV: "test"
  plugins:
    - id: build-blocker-plugin
      version: latest
    - id: authorize-project
      version: latest
    - id: kubernetes
      version: latest
  cascconfig:
    configmap: jenkins-config
  cascsecret: jenkins-admin-secret
  groovysecret: jenkins-groovy-secret
  annotations:
    cnct.io/annotation: "test"
    cnct.io/other-annotation: "other test"
  executors: 5
  adminsecret: jenkins-admin-secret
  service:
    name: jenkins
    servicetype: NodePort
    annotations:
      cnct.io/service-annotation: "test"
      cnct.io/other-service-annotation: "other test"
  storage:
    jobspvc: jenkins
    jobspvcspec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1G

